// Code generated by protoc-gen-go.
// source: github.com/micro/monitor-srv/proto/monitor/monitor.proto
// DO NOT EDIT!

/*
Package go_micro_srv_monitor_monitor is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/monitor-srv/proto/monitor/monitor.proto

It has these top-level messages:
	HealthChecksRequest
	HealthChecksResponse
	ServicesRequest
	ServicesResponse
	StatusRequest
	StatusResponse
	StatsRequest
	StatsResponse
*/
package go_micro_srv_monitor_monitor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_micro_os_monitor "github.com/micro/go-os/monitor/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HealthChecksRequest struct {
	// optional: service name
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	// optional: healthcheck id
	Id     string                                 `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Status go_micro_os_monitor.HealthCheck_Status `protobuf:"varint,3,opt,name=status,enum=go.micro.os.monitor.HealthCheck_Status" json:"status,omitempty"`
	Limit  uint64                                 `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
	Offset uint64                                 `protobuf:"varint,5,opt,name=offset" json:"offset,omitempty"`
}

func (m *HealthChecksRequest) Reset()                    { *m = HealthChecksRequest{} }
func (m *HealthChecksRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthChecksRequest) ProtoMessage()               {}
func (*HealthChecksRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HealthChecksResponse struct {
	Healthchecks []*go_micro_os_monitor.HealthCheck `protobuf:"bytes,1,rep,name=healthchecks" json:"healthchecks,omitempty"`
}

func (m *HealthChecksResponse) Reset()                    { *m = HealthChecksResponse{} }
func (m *HealthChecksResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthChecksResponse) ProtoMessage()               {}
func (*HealthChecksResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HealthChecksResponse) GetHealthchecks() []*go_micro_os_monitor.HealthCheck {
	if m != nil {
		return m.Healthchecks
	}
	return nil
}

type ServicesRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *ServicesRequest) Reset()                    { *m = ServicesRequest{} }
func (m *ServicesRequest) String() string            { return proto.CompactTextString(m) }
func (*ServicesRequest) ProtoMessage()               {}
func (*ServicesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ServicesResponse struct {
	Services []*go_micro_os_monitor.Service `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *ServicesResponse) Reset()                    { *m = ServicesResponse{} }
func (m *ServicesResponse) String() string            { return proto.CompactTextString(m) }
func (*ServicesResponse) ProtoMessage()               {}
func (*ServicesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServicesResponse) GetServices() []*go_micro_os_monitor.Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type StatusRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Limit   int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset  int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	// will break out status by node
	Verbose bool `protobuf:"varint,5,opt,name=verbose" json:"verbose,omitempty"`
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type StatusResponse struct {
	Statuses []*go_micro_os_monitor.Status `protobuf:"bytes,1,rep,name=statuses" json:"statuses,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *StatusResponse) GetStatuses() []*go_micro_os_monitor.Status {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type StatsRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Id      string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Limit   int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset  int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *StatsRequest) Reset()                    { *m = StatsRequest{} }
func (m *StatsRequest) String() string            { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()               {}
func (*StatsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type StatsResponse struct {
	Stats []*go_micro_os_monitor.Stats `protobuf:"bytes,1,rep,name=stats" json:"stats,omitempty"`
}

func (m *StatsResponse) Reset()                    { *m = StatsResponse{} }
func (m *StatsResponse) String() string            { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()               {}
func (*StatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StatsResponse) GetStats() []*go_micro_os_monitor.Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*HealthChecksRequest)(nil), "go.micro.srv.monitor.monitor.HealthChecksRequest")
	proto.RegisterType((*HealthChecksResponse)(nil), "go.micro.srv.monitor.monitor.HealthChecksResponse")
	proto.RegisterType((*ServicesRequest)(nil), "go.micro.srv.monitor.monitor.ServicesRequest")
	proto.RegisterType((*ServicesResponse)(nil), "go.micro.srv.monitor.monitor.ServicesResponse")
	proto.RegisterType((*StatusRequest)(nil), "go.micro.srv.monitor.monitor.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "go.micro.srv.monitor.monitor.StatusResponse")
	proto.RegisterType((*StatsRequest)(nil), "go.micro.srv.monitor.monitor.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "go.micro.srv.monitor.monitor.StatsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Monitor service

type MonitorClient interface {
	HealthChecks(ctx context.Context, in *HealthChecksRequest, opts ...client.CallOption) (*HealthChecksResponse, error)
	Services(ctx context.Context, in *ServicesRequest, opts ...client.CallOption) (*ServicesResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...client.CallOption) (*StatusResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...client.CallOption) (*StatsResponse, error)
}

type monitorClient struct {
	c           client.Client
	serviceName string
}

func NewMonitorClient(serviceName string, c client.Client) MonitorClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.monitor.monitor"
	}
	return &monitorClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *monitorClient) HealthChecks(ctx context.Context, in *HealthChecksRequest, opts ...client.CallOption) (*HealthChecksResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Monitor.HealthChecks", in)
	out := new(HealthChecksResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) Services(ctx context.Context, in *ServicesRequest, opts ...client.CallOption) (*ServicesResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Monitor.Services", in)
	out := new(ServicesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) Status(ctx context.Context, in *StatusRequest, opts ...client.CallOption) (*StatusResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Monitor.Status", in)
	out := new(StatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) Stats(ctx context.Context, in *StatsRequest, opts ...client.CallOption) (*StatsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Monitor.Stats", in)
	out := new(StatsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Monitor service

type MonitorHandler interface {
	HealthChecks(context.Context, *HealthChecksRequest, *HealthChecksResponse) error
	Services(context.Context, *ServicesRequest, *ServicesResponse) error
	Status(context.Context, *StatusRequest, *StatusResponse) error
	Stats(context.Context, *StatsRequest, *StatsResponse) error
}

func RegisterMonitorHandler(s server.Server, hdlr MonitorHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Monitor{hdlr}, opts...))
}

type Monitor struct {
	MonitorHandler
}

func (h *Monitor) HealthChecks(ctx context.Context, in *HealthChecksRequest, out *HealthChecksResponse) error {
	return h.MonitorHandler.HealthChecks(ctx, in, out)
}

func (h *Monitor) Services(ctx context.Context, in *ServicesRequest, out *ServicesResponse) error {
	return h.MonitorHandler.Services(ctx, in, out)
}

func (h *Monitor) Status(ctx context.Context, in *StatusRequest, out *StatusResponse) error {
	return h.MonitorHandler.Status(ctx, in, out)
}

func (h *Monitor) Stats(ctx context.Context, in *StatsRequest, out *StatsResponse) error {
	return h.MonitorHandler.Stats(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/micro/monitor-srv/proto/monitor/monitor.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x93, 0xd2, 0x40,
	0x10, 0x35, 0x1b, 0x92, 0xc5, 0x16, 0xd1, 0x1a, 0xb7, 0xac, 0x54, 0xdc, 0xc3, 0xd6, 0x5c, 0xdc,
	0x12, 0x19, 0x34, 0x1e, 0xdc, 0x9b, 0x65, 0xe9, 0x41, 0xab, 0xf4, 0x32, 0x7b, 0xf5, 0xb2, 0x89,
	0x03, 0x49, 0x2d, 0x61, 0x30, 0x33, 0xe0, 0xd9, 0x3f, 0xe4, 0x0f, 0xf0, 0xd7, 0x99, 0xcc, 0x17,
	0x20, 0x48, 0xe0, 0xb0, 0xa7, 0xd0, 0x6f, 0xde, 0xeb, 0x7e, 0xdd, 0xd3, 0x03, 0x5c, 0x4d, 0x0a,
	0x99, 0x2f, 0x52, 0x92, 0xf1, 0x72, 0x54, 0x16, 0x59, 0xc5, 0x47, 0x25, 0x9f, 0x15, 0x92, 0x57,
	0x43, 0x51, 0x2d, 0x47, 0xf3, 0x8a, 0x4b, 0x87, 0xd8, 0x2f, 0x51, 0x28, 0x3a, 0x9f, 0x70, 0xa2,
	0x14, 0xa4, 0x66, 0x12, 0x7b, 0x66, 0xbe, 0x71, 0xb2, 0x95, 0x77, 0xc2, 0x87, 0x5c, 0xb8, 0x5c,
	0x1b, 0x99, 0x75, 0x46, 0xfc, 0xdb, 0x83, 0x27, 0x9f, 0xd8, 0xcd, 0x54, 0xe6, 0x1f, 0x72, 0x96,
	0xdd, 0x0a, 0xca, 0x7e, 0x2c, 0x98, 0x90, 0x28, 0x82, 0x53, 0xc1, 0xaa, 0x65, 0x91, 0xb1, 0xc8,
	0xbb, 0xf0, 0x2e, 0xef, 0x53, 0x1b, 0xa2, 0x3e, 0x9c, 0x14, 0xdf, 0xa3, 0x13, 0x05, 0xd6, 0xbf,
	0xd0, 0x3b, 0x08, 0x85, 0xbc, 0x91, 0x0b, 0x11, 0xf9, 0x35, 0xd6, 0x4f, 0x9e, 0x13, 0x67, 0x92,
	0x0b, 0xe7, 0x71, 0xad, 0x06, 0xb9, 0x56, 0x74, 0x6a, 0x64, 0xe8, 0x0c, 0x82, 0x69, 0x51, 0x16,
	0x32, 0xea, 0xd4, 0xfa, 0x0e, 0xd5, 0x01, 0x7a, 0x0a, 0x21, 0x1f, 0x8f, 0x05, 0x93, 0x51, 0xa0,
	0x60, 0x13, 0xe1, 0x6f, 0x70, 0xb6, 0xe9, 0x57, 0xcc, 0xf9, 0x4c, 0x30, 0xf4, 0x11, 0x7a, 0xb9,
	0xc2, 0x33, 0x85, 0xd7, 0xae, 0xfd, 0xcb, 0x07, 0xc9, 0x45, 0x9b, 0x19, 0xba, 0xa1, 0xc2, 0x03,
	0x78, 0x74, 0xad, 0xfb, 0x6c, 0x9f, 0x04, 0xfe, 0x02, 0x8f, 0x57, 0x64, 0x63, 0xe3, 0x0a, 0xba,
	0xe6, 0xd8, 0x5a, 0x38, 0xdf, 0x69, 0xc1, 0x08, 0xa9, 0x63, 0xe3, 0x5f, 0x1e, 0x3c, 0x34, 0x93,
	0x39, 0xfa, 0x0e, 0xdc, 0x08, 0x9b, 0x2b, 0xf0, 0xb7, 0x47, 0xd8, 0x51, 0xb0, 0x89, 0x9a, 0xbc,
	0x4b, 0x56, 0xa5, 0x5c, 0x30, 0x35, 0xdb, 0x2e, 0xb5, 0x21, 0xfe, 0x0c, 0x7d, 0x6b, 0xc1, 0xf4,
	0xf3, 0xb6, 0xee, 0x47, 0x21, 0xae, 0x9f, 0x67, 0xbb, 0xfb, 0xd1, 0x32, 0x47, 0xc6, 0x63, 0xe8,
	0x35, 0xd8, 0x5d, 0x37, 0x83, 0xdf, 0xeb, 0xa9, 0xad, 0x1c, 0xbf, 0x82, 0xa0, 0x31, 0x61, 0xed,
	0xc6, 0xff, 0xb5, 0x2b, 0xa8, 0x26, 0x26, 0x7f, 0x7c, 0x38, 0xfd, 0xaa, 0x0f, 0xd0, 0x4f, 0xe8,
	0xad, 0xaf, 0x17, 0x7a, 0x4d, 0xf6, 0x3d, 0x39, 0xb2, 0xe3, 0xe9, 0xc4, 0xc9, 0x31, 0x12, 0x6d,
	0x1a, 0xdf, 0x43, 0xb7, 0xd0, 0xb5, 0xcb, 0x84, 0x86, 0xfb, 0x33, 0xfc, 0xb3, 0xa1, 0x31, 0x39,
	0x94, 0xee, 0x8a, 0x31, 0x08, 0xf5, 0x85, 0xa1, 0x41, 0x8b, 0x76, 0x7d, 0x21, 0xe3, 0x97, 0x87,
	0x91, 0x5d, 0x99, 0x14, 0x02, 0x35, 0x68, 0xf4, 0xa2, 0x5d, 0xe8, 0x8a, 0x0c, 0x0e, 0xe2, 0xda,
	0x1a, 0x69, 0xa8, 0xfe, 0xc7, 0xde, 0xfc, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x72, 0x78, 0x12, 0xa9,
	0x55, 0x05, 0x00, 0x00,
}
