// Code generated by protoc-gen-go.
// source: github.com/micro/monitor-srv/proto/monitor/monitor.proto
// DO NOT EDIT!

/*
Package monitor is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/monitor-srv/proto/monitor/monitor.proto

It has these top-level messages:
	HealthChecksRequest
	HealthChecksResponse
	ServicesRequest
	ServicesResponse
*/
package monitor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import monitor1 "github.com/micro/go-platform/monitor/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type HealthChecksRequest struct {
	Id     string                      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Status monitor1.HealthCheck_Status `protobuf:"varint,2,opt,name=status,enum=HealthCheck_Status" json:"status,omitempty"`
	Limit  uint64                      `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
	Offset uint64                      `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
}

func (m *HealthChecksRequest) Reset()                    { *m = HealthChecksRequest{} }
func (m *HealthChecksRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthChecksRequest) ProtoMessage()               {}
func (*HealthChecksRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type HealthChecksResponse struct {
	Healthchecks []*monitor1.HealthCheck `protobuf:"bytes,1,rep,name=healthchecks" json:"healthchecks,omitempty"`
}

func (m *HealthChecksResponse) Reset()                    { *m = HealthChecksResponse{} }
func (m *HealthChecksResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthChecksResponse) ProtoMessage()               {}
func (*HealthChecksResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HealthChecksResponse) GetHealthchecks() []*monitor1.HealthCheck {
	if m != nil {
		return m.Healthchecks
	}
	return nil
}

type ServicesRequest struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
}

func (m *ServicesRequest) Reset()                    { *m = ServicesRequest{} }
func (m *ServicesRequest) String() string            { return proto.CompactTextString(m) }
func (*ServicesRequest) ProtoMessage()               {}
func (*ServicesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ServicesResponse struct {
	Services []*monitor1.Service `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *ServicesResponse) Reset()                    { *m = ServicesResponse{} }
func (m *ServicesResponse) String() string            { return proto.CompactTextString(m) }
func (*ServicesResponse) ProtoMessage()               {}
func (*ServicesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServicesResponse) GetServices() []*monitor1.Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func init() {
	proto.RegisterType((*HealthChecksRequest)(nil), "HealthChecksRequest")
	proto.RegisterType((*HealthChecksResponse)(nil), "HealthChecksResponse")
	proto.RegisterType((*ServicesRequest)(nil), "ServicesRequest")
	proto.RegisterType((*ServicesResponse)(nil), "ServicesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Monitor service

type MonitorClient interface {
	Services(ctx context.Context, in *ServicesRequest, opts ...client.CallOption) (*ServicesResponse, error)
	HealthChecks(ctx context.Context, in *HealthChecksRequest, opts ...client.CallOption) (*HealthChecksResponse, error)
}

type monitorClient struct {
	c           client.Client
	serviceName string
}

func NewMonitorClient(serviceName string, c client.Client) MonitorClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "monitor"
	}
	return &monitorClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *monitorClient) Services(ctx context.Context, in *ServicesRequest, opts ...client.CallOption) (*ServicesResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Monitor.Services", in)
	out := new(ServicesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) HealthChecks(ctx context.Context, in *HealthChecksRequest, opts ...client.CallOption) (*HealthChecksResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Monitor.HealthChecks", in)
	out := new(HealthChecksResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Monitor service

type MonitorHandler interface {
	Services(context.Context, *ServicesRequest, *ServicesResponse) error
	HealthChecks(context.Context, *HealthChecksRequest, *HealthChecksResponse) error
}

func RegisterMonitorHandler(s server.Server, hdlr MonitorHandler) {
	s.Handle(s.NewHandler(&Monitor{hdlr}))
}

type Monitor struct {
	MonitorHandler
}

func (h *Monitor) Services(ctx context.Context, in *ServicesRequest, out *ServicesResponse) error {
	return h.MonitorHandler.Services(ctx, in, out)
}

func (h *Monitor) HealthChecks(ctx context.Context, in *HealthChecksRequest, out *HealthChecksResponse) error {
	return h.MonitorHandler.HealthChecks(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0x3b, 0x4f, 0xc3, 0x30,
	0x10, 0xee, 0x8b, 0x34, 0x1c, 0xa1, 0x2d, 0x6e, 0x91, 0xa2, 0x4c, 0xc8, 0x2c, 0x5d, 0xea, 0x88,
	0xb0, 0x20, 0x24, 0x26, 0x16, 0x16, 0x16, 0xfa, 0x0b, 0xd2, 0xe0, 0x34, 0x16, 0x49, 0x1d, 0xec,
	0x4b, 0x17, 0xfe, 0x3c, 0xc1, 0x79, 0x90, 0x3e, 0x26, 0xeb, 0x3e, 0x7f, 0x8f, 0xbb, 0x0f, 0x9e,
	0xb6, 0x02, 0x93, 0x62, 0xc3, 0x22, 0x99, 0xf9, 0x99, 0x88, 0x94, 0xf4, 0x33, 0xb9, 0x13, 0x28,
	0xd5, 0x4a, 0xab, 0xbd, 0x9f, 0x2b, 0x89, 0x2d, 0xd2, 0xbc, 0xcc, 0xa0, 0xde, 0xa9, 0x72, 0x2b,
	0x57, 0x79, 0x1a, 0x62, 0x2c, 0x55, 0xd6, 0x6a, 0x0e, 0x1c, 0x2a, 0x25, 0xe5, 0x30, 0x7f, 0xe3,
	0x61, 0x8a, 0xc9, 0x6b, 0xc2, 0xa3, 0x2f, 0xfd, 0xc1, 0xbf, 0x0b, 0xae, 0x91, 0x00, 0x0c, 0xc4,
	0xa7, 0xdb, 0xbf, 0xeb, 0x2f, 0x2f, 0xc9, 0x3d, 0x58, 0x1a, 0x43, 0x2c, 0xb4, 0x3b, 0x28, 0xe7,
	0x49, 0x30, 0x67, 0x1d, 0x05, 0x5b, 0x9b, 0x2f, 0x72, 0x0d, 0x17, 0xa9, 0xc8, 0x04, 0xba, 0xc3,
	0x92, 0x33, 0x22, 0x13, 0xb0, 0x64, 0x1c, 0x6b, 0x8e, 0xee, 0xe8, 0x6f, 0xa6, 0xcf, 0xb0, 0x38,
	0x8c, 0xd1, 0xb9, 0xdc, 0x69, 0x4e, 0x28, 0x38, 0x89, 0xc1, 0x23, 0x83, 0x97, 0x89, 0xc3, 0xe5,
	0x55, 0xe0, 0x74, 0x13, 0x28, 0x85, 0xe9, 0x9a, 0xab, 0xbd, 0x88, 0x78, 0xbb, 0xde, 0x14, 0xc6,
	0xba, 0x82, 0xaa, 0x1d, 0x29, 0x83, 0xd9, 0x3f, 0xa7, 0xf6, 0xf6, 0xc0, 0xae, 0x49, 0x8d, 0xaf,
	0xcd, 0x6a, 0x52, 0xf0, 0x03, 0xe3, 0xf7, 0xaa, 0x07, 0xf2, 0x00, 0x76, 0x23, 0x25, 0x33, 0x76,
	0x94, 0xe4, 0xdd, 0xb0, 0x63, 0x5f, 0xda, 0x23, 0x2f, 0xe0, 0x74, 0xaf, 0x21, 0x0b, 0x76, 0xa6,
	0x43, 0xef, 0x96, 0x9d, 0x3b, 0x99, 0xf6, 0x36, 0x96, 0xa9, 0xfe, 0xf1, 0x37, 0x00, 0x00, 0xff,
	0xff, 0x4c, 0x5c, 0x85, 0x9d, 0xf0, 0x01, 0x00, 0x00,
}
